# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_booklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Booklist')),
            ],
        ),
    ]
